### ISSUE TITLE
The connector can send standard messages

### ISSUE THREAD

**Issue by MarcDavid99** [xatkit-bot-platform/xatkit-facebook-messenger-platform#17]
Related to [UC-1](https://github.com/xatkit-bot-platform/labs-ut-platform/wiki/Use-Cases#uc-1-reply-to-incoming-message)
Also see [Facebook document](https://developers.facebook.com/docs/messenger-platform/policy/policy-overview#standard_messaging)

**Comment by taidopurason** [comment]
Create unit tests in iteration 3
