### ISSUE TITLE
Change MessengerUtil strings to be more informative

### ISSUE THREAD

**Issue by Raud0** [xatkit-bot-platform/xatkit-facebook-messenger-platform#69]
While I was creating the readme, I discovered that our naming convention could be better standardized for context parameters. For example 'payload' should be 'xatkit.messenger.payload'. Or perhaps even 'messenger.payload'? Not really sure.

**Comment by Raud0** [comment]
Oh also, there's a typo. 'refferal' -> 'referral'

**Comment by taidopurason** [comment]
Improved the naming convention of the keys/constants in MessengerUtils. I think the configuration keys will require some documentation in code as well, but perhaps that should go under another issue.

@Raud0, can you review the changes?

**Comment by Raud0** [comment]
Yup, this looks way more structured and solves the gripes I had about some inconsistencies on the use of `xatkit.messenger`. And their grouping looks good as well, if you're just looking at the code and not the README.

There being a difference between `mid` and `mids`, which are pretty much the same thing, still annoys me, but that's on Facebook and their naming convention.
